# Generated by Django 3.2.5 on 2021-07-18 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='english_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='product',
            name='isnew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='korean_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_serving_kcal', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('sodium_mg', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('saturated_fat_g', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('sugars_g', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('caffeine_mg', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('size_ml', models.CharField(max_length=45, null=True)),
                ('size_fluid_ounce', models.CharField(max_length=45, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='AllergyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.allergy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'allergies_products',
            },
        ),
        migrations.AddField(
            model_name='allergy',
            name='products',
            field=models.ManyToManyField(through='products.AllergyProduct', to='products.Product'),
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.menu'),
        ),
    ]
